# Generated by Django 6.0.5 on 2026-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_todotask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
