# Generated by Django 6.0.5 on 2026-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todotask_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='title',
            field=models.CharField(default='Def. title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
